export const DEFAULT_TOPICS = [
  "Human Nature",
  "Skill",
  "Fitness",
  "Food",
  "Health",
  "Finance",
  "Books",
  "History",
  "Travel",
  "Certification",
  "Artificial Inteligence",
  "Prompt Engineering",
  "Economy",
  "Business",
  "Technology",
  "Science",
  "Politics",
];
